<?php
$this->form->setAttrib('class', 'comment-form');

foreach ($this->messages as $message) :
?>
    <li>
        <?php if (null !== $message->by_user): ?>
            <a href="<?php echo ($this->guestToken === true) ? $this->url(array(), 'login') : $message->by_user->profiles[0]->permalink;?>" class="illus">
                <img class="picture" src="<?php echo ($this->guestToken === true) ? $this->url(array(), 'login') : $message->by_user->profiles[0]->getAvatar()->getStaticUrl(array('cropcenterresize' => array('width' => 30, 'height' => 30)))?>" width="30" height="30" alt="" />
            </a>
        <?php else: ?>
            <span class="illus">
                <img class="picture" src="/static/avatar-quiz.png" width="30" height="30" alt="" />
            </span>
        <?php endif; ?>
        <div class="text">
                <p><?php if (null !== $message->by_user && '1' !== $message->is_system): ?><a href="<?php echo ($this->guestToken === true) ? $this->url(array(), 'login') : $message->by_user->profiles[0]->permalink; ?>"><?php echo $message->by_user->profiles[0]; ?></a><?php endif; ?> 
                
                <?php $messageStr = $message->text;
                    echo $messageStr; ?></p>
            <p class="small"><?php echo $this->ago($message->getDateObjectBycreated_at()); ?> - <a class="trigger-comment" href="<?php echo ($this->guestToken === true) ? $this->url(array(), 'login') : $this->url(); ?>#form-<?php echo $message->id; ?>" rel="<?php echo $message->id; ?>"><?php echo $this->translate('commenter'); ?></a></p>
            <div class="comment-wrapper">
                <span class="comment-container">
                    <?php if ($message->walls->count() > $this->messageMax): ?>
                        <p class="comment-more"><a href="<?php echo ($this->guestToken === true) ? $this->url(array(), 'login') : $message->permalink; ?>"><span class="icon icon-comment"></span> <?php echo $this->translate('Voir les %s commentaires', (count($message->walls) - $this->messageMax)); ?></a></p>
                     <?php endif;?>
                     
                    <?php echo $this->partial('wall/messages.phtml', array('message' => $message, 'messageMax' => $this->messageMax)); ?>
                </span>
            <?php 
                $this->form->getElement('response_to_id')->setValue($message->id);
                $this->form->setAttrib('name', 'comment-form-' . $message->id);
                echo $this->form;
            ?>
            </div>
        </div>
        <div class="clear"></div>
    </li>
<?php endforeach; ?>
